ignoreFiles = ["content/portfolio/\\.*","content/product/\\.*","content/sketch/\\.*","content/homepage/\\.*","content/post/\\.*","content/\\.*"] # disable example pages as this is a single page
baseURL = "https://sultanov.github.io/" # https://sultanov.github.io/
title = "Hugo Themes"
# author = "Steve Francia"
# copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
# paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]



# Scroll Spy has problems with german umlauts and other non ascii characters
removePathAccents = true

# Theme specific examples
author = "Fazliddin Sultonov"
copyright = "Fazliddin Sultonov"
googleAnalytics = "G-X7WX2WGMF9"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true
relativeURLs = true
paginate = 6
theme="flex-bp-hugo-cv"

publishDir = "../sultanov.github.io"

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    post = "/:year/:month/:slug/"
    pages = "/:slug/"
    page = "/:slug/"

[Author]  
  name = "Fazliddin Sultonov"

[params]
  description = "Text about the site"
  customDateFormat = "01/2006" # "02.01.2006"
  # js=["/js/test_site.js"]
  # css=["/css/test_site.css"]
  # csscdn=["https://fonts.googleapis.com/css?family=Concert+One|Roboto&display=swap"]


[languages]
  [languages.en]
    languageName = "EN"
    title = "CV"
    weight = 1
    [languages.en.params]
  [languages.de]
    languageName = "DE"
    title = "Lebenslauf"
    weight = 2
    [languages.de.params]
  [languages.ru]
    languageName = "RU"
    title = "Резюме"
    weight = 3
    [languages.ru.params]

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted.
# Code from https://themes.gohugo.io/future-imperfect/ theme
[social]
  # Coding Communities
  github           = "FaziSultan"
  gitlab           = ""
  stackoverflow    = "" # User Number
  bitbucket        = ""
  jsfiddle         = ""
  codepen          = ""
  # Visual Art Communities
  deviantart       = ""
  flickr           = ""
  behance          = ""
  dribbble         = ""
  # Publishing Communities
  wordpress        = ""
  medium           = ""
  # Professional/Business Oriented Communities
  linkedin         = "fazliddinsultonov"
  linkedin_company = ""
  foursquare       = ""
  xing             = "Fazliddin_Sultonov3"
  slideshare       = ""
  # Social Networks
  facebook         = "" # https://fb.me/flowartsde
  googleplus       = ""
  reddit           = ""
  quora            = ""
  youtube          = "UC1vH3m44feh4WzQWQQBMong" 
  vimeo            = ""
  whatsapp         = "" # WhatsApp Number
  instagram        = "f_sultonov"
  tumblr           = ""
  twitter          = "Fazil_BEK"
  skype            = ""
  snapchat         = ""
  pinterest        = ""
  telegram         = "f_sultan"
  discord          = "" # invite link
  # Email
  email            = ""


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
